version: '3.7'

services:

  react-restaurant-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/restaurant-app'
      - '/restaurant-app/node_modules'
    ports:
      - 3069:3000
    expose:
      - "3069"
    environment:
      - CHOKIDAR_USEPOLLING=true