export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REDUCE_INGREDIENT = 'REDUCE_INGREDIENT';

export const CHANGE_INPUT_BOOKING_VALUE = 'CHANGE_INPUT_BOOKING_VALUE';

export const CHANGE_INPUT_DISH_VALUE = 'CHANGE_INPUT_DISH_VALUE';